#!/bin/bash

export DISPLAY=:0

WORKPATH=`pwd`
JAR="${WORKPATH}/selenium-server-standalone-2.45.0.jar"
LOGFILE="${WORKPATH}/selenium-server.log"
PROFILE="${WORKPATH}/profile"
TIMEOUT=180000

BIN=`which java`
NAME="Selenium Server"
ARGS="-jar ${JAR} -firefoxProfileTemplate ${PROFILE} -timeout ${TIMEOUT} -trustAllSSLCertificates -log ${LOGFILE}"
PIDFILE="/tmp/selenium-server.pid"

case "$1" in
  start)
    echo -ne "Starting ${NAME}: "
    start-stop-daemon --start --quiet \
                      --background \
                      --pidfile $PIDFILE --make-pidfile \
                      --exec $BIN \
                      -- $ARGS
    echo " ....OK"
    ;;
  stop)
    echo -ne "Stopping ${NAME}: "
    start-stop-daemon --stop --quiet \
                      --pidfile $PIDFILE
    rm -f $PIDFILE
    echo " ....OK"
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "Usage: ${0} {start|stop|restart}"
    exit 1
esac

exit 0
