#!/bin/bash

BIN=`which php`
NAME="PHP Web Server"
PORT=`(netstat  -atn | awk '{printf "%s\n%s\n", $4, $4}' | grep -oE '[0-9]*$'; seq 8000 9000) | sort -n | uniq -u | head -n 1`
WEBPATH=${2-`pwd`}
PIDFILE="/tmp/php-web-server-${PORT}.pid"
ARGS="-S localhost:${PORT} -t ${WEBPATH}"

case "$1" in
  start)
    echo -ne "Starting ${NAME}: "
    start-stop-daemon --start --quiet \
                      --background \
                      --pidfile $PIDFILE --make-pidfile \
                      --exec $BIN \
                      -- $ARGS
    echo " ....OK"
    ;;
  stop)
    echo -ne "Stopping ${NAME}: "
    start-stop-daemon --stop --quiet \
                      --pidfile $PIDFILE
    rm -f $PIDFILE
    echo " ....OK"
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "Usage: ${0} {start|stop|restart}"
    exit 1
esac

exit 0
