#!/bin/bash

BIN=`which Xvfb`
NAME="X virtual framebuffer"
ARGS=":0 -screen 0 1280x1024x24 -fbdir /tmp -ac -render"
PIDFILE=/tmp/xvfb.pid

case "$1" in
  start)
    echo -ne "Starting ${NAME}: "
    start-stop-daemon --start --quiet \
                      --background \
                      --pidfile $PIDFILE --make-pidfile \
                      --exec $BIN \
                      -- $ARGS
    echo " ....OK"
    ;;
  stop)
    echo -ne "Stopping ${NAME}: "
    start-stop-daemon --stop --quiet \
                      --pidfile $PIDFILE
    rm -f $PIDFILE
    echo " ....OK"
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "Usage: ${0} {start|stop|restart}"
    exit 1
esac

exit 0
